### ISSUE TITLE
Файл `app-order.jar` в IDEA не запускается при проверке формы заказа карты

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/AutoTestDZ_3.1_SeleniumSelenide#1]
## Описание 
Файл `app-order.jar` размещен в каталоге `artifacts` проекта [AutoTestDZ_3.1_SeleniumSelenide](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide) . Файл был скопирован из репозитория GitHab c этого URL `https://github.com/netology-code/aqa-homeworks/blob/master/web/app-order.jar`. При обращении к нему, для запуска на локальном сервере, командой `java -jar app-order.jar`. Выдает ошибку `Error: Invalid or corrupt jarfile app-order.jar`. Форма оформления карты не запускается.

## Локация дефекта
https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/blob/main/artifacts/app-order.jar

## Шаги воспроизведения

1. открыть проект на GitHab по ссылке:[AutoTestDZ_3.1_SeleniumSelenide](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide);
2. Скопировать `app-order.jar` своё устройство;
3. запустить через консоль командой `java -jar app-order.jar`;

***Ожидаемый результат:***
Запуститься форма оформления карты.
***Фактический результат:***
Выдает ошибку  `Error: Invalid or corrupt jarfile app-order.jar`.

## Скриншот

![Bag app-order](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/assets/149007689/9566f59d-f4e1-4f8b-be63-76e0afb0984b)

## Окружение

- Характеристики Windows:

Выпуск Windows 10 Домашняя
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by andrew-pahomov** [comment]
Jar файл поврежден, рекомендую закачать его повторно.
