### ISSUE TITLE
Тестовые атрибуты `data-test-id=...form` и `data-test-id=submit`  отсутствуют в коде формы для тестирования

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/AutoTestDZ_3.1_SeleniumSelenide#2]
## Описание 
В коде формы `http://localhost:9999` для заявки на карту отсутствуют тестовые атрибуты `data-test-id=...form` в активной части, предназначенной для заполнения пользователем. Присутствуют атрибуты на структурные элементы `data-test-id=name`, `data-test-id=phone`, `data-test-id=agreement`.

## Локация дефекта
1. `<form action="/" enctype="application/x-www-form-urlencoded" method="post" autocomplete="on" class="form form_size_m form_theme_alfa-on-white">`
2. `<button role="button" type="button" class="button button_view_extra button_size_m button_theme_alfa-on-white"><span class="button__content"><span class="button__text">Продолжить</span></span></button>`

## Шаги воспроизведения

1. Через терминал запустить  ` java -jar app-order.jar`.
2. Открыть в браузере ссылку `http://localhost:9999` .
4. ОТкрыть консоль браузера (F12).
7. Посмотреть код.

***Ожидаемый результат:*** 
Наличие атрибутов для тестирования активной формы `data-test-id=...form` и кнопки продолжить в ней `data-test-id=submit`.

***Фактический результат:***
Отсутствие атрибутов для тестирования активной формы `data-test-id=...form` и кнопки продолжить в ней `data-test-id=submit`.

## Скриншот

![AvailabilityOfAttributes1](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/assets/149007689/8e857669-78ee-4fbb-8b12-a232a3e4248a)

![AvailabilityOfAttributes2](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/assets/149007689/5bfd91f9-83a3-44b8-ac26-f7e53124d8d5)

## Окружение
- Характеристики Windows:
Выпуск Windows 10 Домашняя
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by andrew-pahomov** [comment]
Честно говоря не понял сути проблемы, в структуре странице есть тестовые метки, используйте их для реализации автотестов.

**Comment by migbaranes** [comment]
НЕАКТУАЛЬНО
