### ISSUE TITLE
Build failed при `PUSH` на `GitHub`

### ISSUE THREAD

**Issue by migbaranes** [migbaranes/AutoTestDZ_3.1_SeleniumSelenide#3]
## Описание 
Автотесты проекта ***локально*** проходят. Настройка проекта `dependencies` и `gradle.yml` выполнены по условию ДЗ. Комбинировал различные версии `org.seleniumhq.selenium:selenium-java:4.11.0` и `io.github.bonigarcia:webdrivermanager:5.3.0`.
При отправке на `GitHub` ***Build failed***.

## Локация дефекта
https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/actions/runs/7826475295/job/21352410891

## Шаги воспроизведения

1. Выполнить git clone проекта из удаленного репозитория.
2. Открыть в IDEA .
3. Выполнить git pufh в удаленный репозиторий.
4 Посмотреть результат.

***Ожидаемый результат:*** 
Сборка проходит CI.

***Фактический результат:***
Сборка ytпроходит CI.

## Скриншот
![Build Failed1](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/assets/149007689/8371a330-92b6-42e3-a796-baee47a90b9d)
![Build Failed2 gif](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/assets/149007689/99d97d50-2fac-4747-a2c0-b14a7c3344d9)

_Предупреждение при локальном запуске_
![Build Failed3 gif](https://github.com/migbaranes/AutoTestDZ_3.1_SeleniumSelenide/assets/149007689/45d9d612-0bf1-43e5-9007-92710cdd1b7d)

## Окружение
- Характеристики Windows:
Выпуск Windows 10 Домашняя
Версия 22H2
Дата установки ‎23.‎03.‎2023
Сборка ОС 22621.2428
Взаимодействие Windows Feature Experience Pack 1000.22674.1000.0

- IDE IntelliJ IDEA 2023.2.5

- JAVA corretto-11.0.21

**Comment by andrew-pahomov** [comment]
Вы не обеспечили headless режим запуска браузера в CI.
